paths: 
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags: 
        - Products
      responses:
        "200":
          description: Los usuarios fueron obtenidos correctamente
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del server, usualmente generado por una query defectuosa
   
